# Site settings
title: Magic Grant Fall Showcase
email: amccartn@stanford.edu
url: brown.stanford.edu
description: "Join the Brown Institute for Media Innovation at Stanford for a showcase of Magic Grant-funded digital media projects."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#FFFFFF'
  links: '#8C1515'

location: '350 Serra Mall Stanford, CA 94305'

# Footer settings
footer: The Brown Institute for Media Innovation

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/BrownInstitute
  - title: facebook
    url: https://www.facebook.com/MadeAtBrown

# Build settings
markdown: kramdown
permalink: pretty
